from django.db import models
from django.contrib.auth.models import User

class Encounter(models.Model):
    subjectID =                     models.CharField(max_length=200)
    administrationNumber =          models.CharField(max_length=200)
    dateOfQuestionaire =            models.DateTimeField()
    dateCreated =                   models.DateTimeField()
    createdBy =                     models.CharField(max_length=200)

class CoverSheet(models.Model):
    encounter =                     models.ForeignKey(Encounter)
    question1 =                     models.CharField(max_length=5,null=True)
    question1a =                    models.IntegerField(null=True)
    question2 =                     models.CharField(max_length=5,null=True)
    question2a =                    models.IntegerField(null=True)
    question2b =                    models.CharField(max_length=200,null=True)
    question2c =                    models.CharField(max_length=200,null=True)
    question3 =                     models.CharField(max_length=5,null=True)
    question4 =                     models.IntegerField(null=True)
    question4a =                    models.CharField(max_length=200,null=True)
    question4b =                    models.CharField(max_length=200,null=True)
    question5 =                     models.CharField(max_length=200,null=True)
    memoryProblems =                models.CharField(max_length=5,null=True)
    balanceProblems =               models.CharField(max_length=5,null=True)
    dizziness =                     models.CharField(max_length=5,null=True)
    sensitivityToLight =            models.CharField(max_length=5,null=True)
    sensitivityToNoise =            models.CharField(max_length=5,null=True)
    ringingInTheEars =              models.CharField(max_length=5,null=True)
    irritability =                  models.CharField(max_length=5,null=True)
    headaches =                     models.CharField(max_length=5,null=True)
    sleepProblems =                 models.CharField(max_length=5,null=True)
    disorientation =                models.CharField(max_length=5,null=True)
    troubleTrackingConv =           models.CharField(max_length=5,null=True)
    lossOfHearing =                 models.CharField(max_length=5,null=True)
    vomitingOrNausea =              models.CharField(max_length=5,null=True)
    changeInVision =                models.CharField(max_length=5,null=True)
    otherSymptoms =                 models.CharField(max_length=200,null=True)
    NoSymptoms =                    models.CharField(max_length=5,null=True)

class NonBlastHeadInjury(models.Model):
    encounter =                     models.ForeignKey(Encounter)
    eventDetailSummary =            models.TextField(null=True)
    eventDetailQuestion1 =          models.DateTimeField(null=True)
    eventDetailQuestion2 =          models.IntegerField(null=True)
    eventDetailQuestion3 =          models.CharField(max_length=5,null=True)
    eventDetailQuestion4 =          models.CharField(max_length=5,null=True)
    eventDetailQuestion4a =         models.CharField(max_length=5,null=True)
    eventDetailQuestion5 =          models.CharField(max_length=5,null=True)
    eventDetailQuestion5a =         models.CharField(max_length=5,null=True)
    eventDetailQuestion6 =          models.CharField(max_length=5,null=True)
    eventDetailQuestion6a =         models.CharField(max_length=500,null=True)
    eventDetailQuestion7 =          models.CharField(max_length=5,null=True)
    eventDetailQuestion7a =         models.CharField(max_length=500,null=True)
    eventDetailQuestion8 =          models.CharField(max_length=5,null=True)
    eventDetailQuestion8a =         models.IntegerField(null=True)
    eventDetailQuestion9 =          models.CharField(max_length=100,null=True)
    eventDetailQuestion10 =         models.CharField(max_length=5,null=True)
    eventDetailQuestion10a =        models.CharField(max_length=5,null=True)
    eventDetailQuestion11 =         models.CharField(max_length=50,null=True)
    eventDetailQuestion11a =        models.CharField(max_length=50,null=True)
    eventDetailQuestion11b =        models.CharField(max_length=50,null=True)
    memoryQuestion1 =               models.CharField(max_length=5,null=True)
    memoryQuestion2 =               models.CharField(max_length=5,null=True)
    memoryQuestion2a =              models.CharField(max_length=500,null=True)
    memoryQuestion2b =              models.CharField(max_length=100,null=True)
    memoryQuestion3 =               models.CharField(max_length=5,null=True)
    memoryQuestion3a =              models.CharField(max_length=500,null=True)
    memoryQuestion3b =              models.CharField(max_length=100,null=True)
    memoryQuestion4 =               models.CharField(max_length=5,null=True)
    consciousnessQuestion1 =        models.CharField(max_length=5,null=True)
    consciousnessQuestion1a =       models.CharField(max_length=100,null=True)
    consciousnessQuestion1b =       models.CharField(max_length=100,null=True)
    consciousnessQuestion1c =       models.CharField(max_length=100,null=True)
    headacheQuestion1 =             models.CharField(max_length=5,null=True)
    headacheQuestion1a =            models.CharField(max_length=100,null=True)
    headacheQuestion1b =            models.CharField(max_length=100,null=True)
    headacheQuestion1c =            models.CharField(max_length=10,null=True)
    headacheQuestion1c1 =           models.CharField(max_length=10,null=True)
    headacheQuestion1d =            models.CharField(max_length=100,null=True)
    headacheQuestion1d1 =           models.IntegerField(null=True)
    dizzinessQuestion1 =            models.CharField(max_length=5,null=True)
    dizzinessQuestion1a =           models.CharField(max_length=100,null=True)
    dizzinessQuestion1b =           models.CharField(max_length=100,null=True)
    dizzinessQuestion1c =           models.CharField(max_length=100,null=True)
    dizzinessQuestion1c1 =          models.CharField(max_length=100,null=True)
    disorientationQuestion1 =       models.CharField(max_length=5,null=True)
    disorientationQuestion1a =      models.CharField(max_length=100,null=True)
    disorientationQuestion1b =      models.CharField(max_length=100,null=True)
    disorientationQuestion1c =      models.CharField(max_length=100,null=True)
    disorientationQuestion1c1 =     models.CharField(max_length=100,null=True)
    irritabilityQuestion1 =         models.CharField(max_length=5,null=True)
    irritabilityQuestion1a =        models.CharField(max_length=100,null=True)
    irritabilityQuestion1b =        models.CharField(max_length=100,null=True)
    irritabilityQuestion1c =        models.CharField(max_length=100,null=True)
    irritabilityQuestion1c1 =       models.CharField(max_length=100,null=True)
    troubleTrackQuestion1 =         models.CharField(max_length=5,null=True)
    troubleTrackQuestion1a =        models.CharField(max_length=100,null=True)
    troubleTrackQuestion1b =        models.CharField(max_length=100,null=True)
    troubleTrackQuestion1c =        models.CharField(max_length=100,null=True)
    troubleTrackQuestion1c1 =       models.CharField(max_length=100,null=True)
    ringingInEarsQuestion1 =        models.CharField(max_length=5,null=True)
    ringingInEarsQuestion1a =       models.CharField(max_length=100,null=True)
    ringingInEarsQuestion1b =       models.CharField(max_length=100,null=True)
    ringingInEarsQuestion1c =       models.CharField(max_length=100,null=True)
    ringingInEarsQuestion1c1 =      models.CharField(max_length=100,null=True)
    sensitivityToNoiseQuestion1 =   models.CharField(max_length=5,null=True)
    sensitivityToNoiseQuestion1a =  models.CharField(max_length=100,null=True)
    sensitivityToNoiseQuestion1b =  models.CharField(max_length=100,null=True)
    sensitivityToNoiseQuestion1c =  models.CharField(max_length=100,null=True)
    sensitivityToNoiseQuestion1c1 = models.CharField(max_length=100,null=True)
    lossOfHearingQuestion1 =        models.CharField(max_length=5,null=True)
    lossOfHearingQuestion1a =       models.CharField(max_length=100,null=True)
    lossOfHearingQuestion1b =       models.CharField(max_length=100,null=True)
    lossOfHearingQuestion1c =       models.CharField(max_length=100,null=True)
    lossOfHearingQuestion1d =       models.CharField(max_length=100,null=True)
    lossOfHearingQuestion1c1 =      models.CharField(max_length=100,null=True)
    vomitingOrNauseaQuestion1 =     models.CharField(max_length=5,null=True)
    vomitingOrNauseaQuestion1a =    models.CharField(max_length=100,null=True)
    vomitingOrNauseaQuestion1b =    models.CharField(max_length=100,null=True)
    vomitingOrNauseaQuestion1c =    models.CharField(max_length=100,null=True)
    vomitingOrNauseaQuestion1c1 =   models.CharField(max_length=100,null=True)
    sensitivityToLightQuestion1 =   models.CharField(max_length=5,null=True)
    sensitivityToLightQuestion1a =  models.CharField(max_length=100,null=True)
    sensitivityToLightQuestion1b =  models.CharField(max_length=100,null=True)
    sensitivityToLightQuestion1c =  models.CharField(max_length=100,null=True)
    sensitivityToLightQuestion1c1 = models.CharField(max_length=100,null=True)
    changeInVisionQuestion1 =       models.CharField(max_length=5,null=True)
    changeInVisionQuestion1a =      models.CharField(max_length=100,null=True)
    changeInVisionQuestion1b =      models.CharField(max_length=100,null=True)
    changeInVisionQuestion1c =      models.CharField(max_length=100,null=True)
    changeInVisionQuestion1c1 =     models.CharField(max_length=100,null=True)
    memoryProblemsQuestion1 =       models.CharField(max_length=5,null=True)
    memoryProblemsQuestion1a =      models.CharField(max_length=100,null=True)
    memoryProblemsQuestion1b =      models.CharField(max_length=100,null=True)
    memoryProblemsQuestion1c =      models.CharField(max_length=100,null=True)
    memoryProblemsQuestion1c1 =     models.CharField(max_length=100,null=True)
    balanceProblemsQuestion1 =      models.CharField(max_length=5,null=True)
    balanceProblemsQuestion1a =     models.CharField(max_length=100,null=True)
    balanceProblemsQuestion1b =     models.CharField(max_length=100,null=True)
    balanceProblemsQuestion1c =     models.CharField(max_length=100,null=True)
    balanceProblemsQuestion1c1 =    models.CharField(max_length=100,null=True)
    otherProblemsQuestion1 =        models.CharField(max_length=5,null=True)
    otherProblemsQuestion1a =       models.CharField(max_length=100,null=True)
    otherProblemsQuestion1a1 =      models.CharField(max_length=100,null=True)
    otherProblemsQuestion1a2 =      models.CharField(max_length=100,null=True)
    otherProblemsQuestion1a3 =      models.CharField(max_length=100,null=True)
    otherProblemsQuestion1a4 =      models.CharField(max_length=100,null=True)
    otherProblemsQuestion1b =       models.CharField(max_length=100,null=True)
    otherProblemsQuestion1b1 =      models.CharField(max_length=100,null=True)
    otherProblemsQuestion1b2 =      models.CharField(max_length=100,null=True)
    otherProblemsQuestion1b3 =      models.CharField(max_length=100,null=True)
    otherProblemsQuestion1b4 =      models.CharField(max_length=100,null=True)
    otherProblemsQuestion1c =       models.CharField(max_length=100,null=True)
    otherProblemsQuestion1c1 =      models.CharField(max_length=100,null=True)
    otherProblemsQuestion1c2 =      models.CharField(max_length=100,null=True)
    otherProblemsQuestion1c3 =      models.CharField(max_length=100,null=True)
    otherProblemsQuestion1c4 =      models.CharField(max_length=100,null=True)
    TBIClassification =             models.CharField(max_length=100,null=True)
    dateSinceInjury =               models.CharField(max_length=100,null=True)

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    #website = models.URLField(blank=True)
    #picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username